name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make venv

    - name: Install dependencies 2
      run: make install

    - name: Test model.py
      run: make model-test

    - name: Test api.py
      run: make api-test
